## ----------------------------------------------------------------------------
## nexus | NEW_MigdalSignal.init.mac
##
## Initialization macro to simulate neutrons from a specific vertex
## in the NEW detector.
##
## The NEXT Collaboration
## ----------------------------------------------------------------------------
##### VERBOSITY #####
#/run/verbose 0
#/event/verbose 0
#/tracking/verbose 0

### PHYSICS
/PhysicsList/RegisterPhysics G4EmStandardPhysics_option4
/PhysicsList/RegisterPhysics G4EmExtraPhysics
/PhysicsList/RegisterPhysics G4DecayPhysics
/PhysicsList/RegisterPhysics G4RadioactiveDecayPhysics
/PhysicsList/RegisterPhysics G4HadronElasticPhysicsHP
/PhysicsList/RegisterPhysics G4HadronPhysicsQGSP_BERT_HP
/PhysicsList/RegisterPhysics G4StoppingPhysics
/PhysicsList/RegisterPhysics G4IonPhysics
/PhysicsList/RegisterPhysics G4OpticalPhysics
/PhysicsList/RegisterPhysics NexusPhysics
/PhysicsList/RegisterPhysics G4StepLimiterPhysics


### GEOMETRY
/Geometry/RegisterGeometry NEXT_NEW

### GENERATOR
/Generator/RegisterGenerator MIGDAL

### ACTIONS
/Actions/RegisterRunAction DEFAULT
/Actions/RegisterEventAction DEFAULT
/Actions/RegisterTrackingAction DEFAULT

### CONFIGURATION
/nexus/RegisterMacro macros/NEW_MigdalSignal.config.mac
